### ISSUE TITLE
EC2PortRange is empty (missing From and To fields)

### ISSUE THREAD

**Issue by matt-duch** [crewjam/go-cloudformation#10]
schema.go L7269-7273 contains:
// EC2PortRange represents EC2 PortRange Property Type
//
// see http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-port-range.html
type EC2PortRange struct {
}

struct should be:
type EC2PortRange struct {
	From *IntegerExpr
	To   *IntegerExpr
}

**Comment by crewjam** [comment]
Thanks for the report. I hacked at the scraper so that the generated structure has those properties. Please let me know if that fixes it for you. -R
