### ISSUE TITLE
Support CustomResource provider params

### ISSUE THREAD

**Issue by mweagle** [crewjam/go-cloudformation#2]
Hi @crewjam ,
I need to be able to set provider specific [CustomResource properties](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html), but it doesn't look as though [CloudFormationCustomResource](https://godoc.org/github.com/crewjam/go-cloudformation#CloudFormationCustomResource) supports that.  

Is this something on your backlog?  I'd be happy to work on a PR to add this if you can give me some pointers on where to start.  Thanks.

**Comment by crewjam** [comment]
So this is an interesting problem, and one I was destined to encounter as we convert our stuff over to use the library. 

I think our approach depends on how committed we are to being type safe. The cleanest way I can think of to solve it is to create a type for your custom resource that implements the cloudformation.ResourceProperties interface:

    type MyResource struct {
        CloudFormationCustomResource
        Foo *cloudformation.String
        Bar *cloudformation.Bool
    }
      
If this type implements `cloudformation.ResourceProperties` the it can be used as a resource. Using this approach, all we'd need to do is add an example / documentation describing the approach.

A less-type-safe approach is to add a `map[string]interface{}` somewhere, which I think is slightly less desirable, but I'm open to it.

Thoughts?

**Comment by crewjam** [comment]
Additional thought:

Supporting custom resource types would mean refactoring NewResourceByType() to have some kind of init-time registration rather than a big generated switch (https://github.com/crewjam/go-cloudformation/blob/master/schema.go#L10075).

**Comment by mweagle** [comment]
> If this type implements cloudformation.ResourceProperties the it can be used as a resource. Using this approach, all we'd need to do is add an example / documentation describing the approach.

I like that approach - it seems consistent with the rest of the library's focus on type safety.  Also, since custom resources are by definition domain specific, seems like a good opportunity to be explicit about the data model. Always a good thing :)

If it's ok with you, I'll work on a PR.  Thanks for the pointers.

**Comment by crewjam** [comment]
Sounds great, thanks!

**Comment by mweagle** [comment]
Will do - how does something like this look to you:

```go

type MyResource struct {
	CloudFormationCustomResource
	Foo *StringExpr
}

func customTypeProvider(resourceType string) ResourceProperties {
	switch resourceType {
	case "Custom::MyResource":
		return &MyResource{}
	}
	return nil
}

func init() {
	RegisterCustomResourceProvider(customTypeProvider)
}

func TestCustomResource(t *testing.T) {
	myResourceInstance, ok := NewResourceByType("Custom::MyResource").(*MyResource)
	if !ok {
		t.Fatalf("Failed to call user provided CustomResourceProvider")
	}
```

**Comment by crewjam** [comment]
So the semantics are that NewResourceByType invokes each custom type provider until one of them returns non-nil? That seems reasonable to me. :+1: 

Thanks for working on this!

**Comment by mweagle** [comment]
Hi @crewjam  - ok to close this given https://github.com/crewjam/go-cloudformation/pull/3?  Thanks.

**Comment by crewjam** [comment]
:+1:
